{
    "name": "Generic Background Service",
    "version": "18.0.0.1.3",
    "author": "Center of Research and Development",
    "website": "https://crnd.pro",
    "license": "LGPL-3",
    "summary": """True background services for Odoo""",
    'category': 'Technical Settings',
    'depends': [],
    'demo': [],
    'data': [],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
}
